# Generated by Django 3.1.3 on 2020-11-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elector_id', models.CharField(max_length=10, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('front_picture', models.ImageField(upload_to='media/elector/front_picture/')),
                ('left_side_picture', models.ImageField(upload_to='media/elector/left_side_picture/')),
                ('right_side_picture', models.ImageField(upload_to='media/elector/right_side_picture/')),
                ('sexe', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255, null=True)),
                ('date_of_issuance', models.DateField(auto_now_add=True)),
                ('date_of_expire', models.DateField(null=True)),
            ],
        ),
    ]
