# Generated by Django 3.1.3 on 2020-11-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='elector_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
