# Generated by Django 3.1.3 on 2020-11-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0002_auto_20201108_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='elector_id',
            field=models.CharField(editable=False, max_length=255, null=True, unique=True),
        ),
    ]
