# Generated by Django 3.1.3 on 2020-11-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0003_auto_20201108_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='front_picture',
            field=models.ImageField(upload_to='elector/front_picture/'),
        ),
        migrations.AlterField(
            model_name='elector',
            name='left_side_picture',
            field=models.ImageField(upload_to='elector/left_side_picture/'),
        ),
        migrations.AlterField(
            model_name='elector',
            name='right_side_picture',
            field=models.ImageField(upload_to='elector/right_side_picture/'),
        ),
    ]
