# Generated by Django 3.1.3 on 2020-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0004_auto_20201108_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='has_vote',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
