# Generated by Django 3.1.3 on 2020-11-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0005_elector_has_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='candidate_id',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
