# Generated by Django 3.1.3 on 2020-12-21 15:06

from django.db import migrations, models
import elector.models


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0006_elector_candidate_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('electorId', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='elector',
            name='front_picture',
            field=models.ImageField(upload_to=elector.models.front_upload_to),
        ),
        migrations.AlterField(
            model_name='elector',
            name='left_side_picture',
            field=models.ImageField(upload_to=elector.models.left_upload_to),
        ),
        migrations.AlterField(
            model_name='elector',
            name='right_side_picture',
            field=models.ImageField(upload_to=elector.models.right_upload_to),
        ),
    ]
