# Generated by Django 3.1.3 on 2021-01-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0007_auto_20201221_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elector',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='elector',
            name='has_vote',
        ),
    ]
