# Generated by Django 3.1.3 on 2020-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canditate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
