# Generated by Django 3.1.3 on 2020-12-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canditate', '0003_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
