# Generated by Django 3.1.3 on 2020-12-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canditate', '0004_vote_vote_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='picture',
            field=models.ImageField(null=True, upload_to='candidates'),
        ),
    ]
