# Generated by Django 3.1.3 on 2020-12-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canditate', '0005_auto_20201221_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
