# Generated by Django 3.1.3 on 2020-12-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canditate', '0006_auto_20201226_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_description',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
