# Generated by Django 3.1.3 on 2020-12-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canditate', '0007_auto_20201226_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
