# Generated by Django 3.1.3 on 2020-12-25 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_auto_20201225_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='survery',
            new_name='survey',
        ),
        migrations.AddField(
            model_name='submission',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
