# Generated by Django 3.1.3 on 2020-12-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20201225_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='proposition',
            field=models.ManyToManyField(blank=True, to='survey.Proposition'),
        ),
    ]
