# Generated by Django 3.1.3 on 2020-12-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elector', '0007_auto_20201221_1506'),
        ('survey', '0005_auto_20201225_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='elector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='elector.elector'),
        ),
        migrations.AddField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
    ]
