# Generated by Django 3.1.3 on 2020-12-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20201225_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
