# Generated by Django 3.1.3 on 2020-12-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_auto_20201226_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='proposition',
        ),
        migrations.AddField(
            model_name='question',
            name='proposition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Proposition',
        ),
    ]
