# Generated by Django 3.1.3 on 2020-12-28 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20201228_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='proposition',
            new_name='choices',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RADIO BUTTON', 'Radio Button'), ('TEXT', 'Text'), ('NUMERICINPUT', 'Numeric'), ('MULTISELECT', 'Multiselect')], default='RADIO BUTTON', max_length=255),
        ),
    ]
