# Generated by Django 3.1.3 on 2021-01-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20201228_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TextInput', 'TextInput'), ('NumericInput', 'NumericInput'), ('SelectionGroup', 'SelectionGroup'), ('MultipleSelectionGroup', 'MultipleSelectionGroup')], default='TextInput', max_length=255),
        ),
    ]
